---
driver_plugin: vagrant 
driver_config:
  require_chef_omnibus: latest

platforms:
- name: debian-7.4
  run_list:
  - recipe[apt]
- name: ubuntu-12.04 
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  run_list:
    recipe[apt]
- name: centos-6.5
- name: centos-5.10

suites:
- name: default
  run_list: ["recipe[nfs::server]"]
  attributes: {}
