---
driver_plugin: vagrant

platforms:
- name: debian-7.4
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: centos-7.0
- name: centos-7.1
- name: centos-6.5
- name: centos-5.10

suites:
- name: default
  run_list:
  - recipe[nfs::default]
- name: server
  run_list:
  - recipe[nfs::server]
  - recipe[nfs_test::server]
  - recipe[nfs_test::issue46]
# - name: server4
#   run_list:
#   - recipe[nfs::server4]
#   - recipe[nfs_test::server]
#   - recipe[nfs_test::issue46]
