---
driver_plugin: vagrant 
driver_config:
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04 
  run_list:
  - recipe[apt]
  driver_config:
    box: opscode-ubuntu-12.04
- name: ubuntu-10.04
  run_list:
  - recipe[apt]
  driver_config:
    box: opscode-ubuntu-10.04
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9

suites:
- name: default
  run_list: ["recipe[nfs::server]"]
  attributes: {}
